### ISSUE TITLE
python2 setup.py test

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#101]
Собственно в питоне ничего не понимаю, хотел в спек добавить проверку и вот что вижу
```
[maxim@ip204-233 foobnix-3.1.01]$ python2 setup.py test
generating dist/share/locale/tr/LC_MESSAGES/foobnix.mo
generating dist/share/locale/si/LC_MESSAGES/foobnix.mo
generating dist/share/locale/pl/LC_MESSAGES/foobnix.mo
generating dist/share/locale/pt_BR/LC_MESSAGES/foobnix.mo
generating dist/share/locale/en_GB/LC_MESSAGES/foobnix.mo
generating dist/share/locale/id/LC_MESSAGES/foobnix.mo
generating dist/share/locale/be/LC_MESSAGES/foobnix.mo
generating dist/share/locale/eo/LC_MESSAGES/foobnix.mo
generating dist/share/locale/pt/LC_MESSAGES/foobnix.mo
generating dist/share/locale/cs/LC_MESSAGES/foobnix.mo
generating dist/share/locale/it/LC_MESSAGES/foobnix.mo
generating dist/share/locale/bg/LC_MESSAGES/foobnix.mo
generating dist/share/locale/et/LC_MESSAGES/foobnix.mo
generating dist/share/locale/es/LC_MESSAGES/foobnix.mo
generating dist/share/locale/ru/LC_MESSAGES/foobnix.mo
generating dist/share/locale/fi/LC_MESSAGES/foobnix.mo
generating dist/share/locale/uk/LC_MESSAGES/foobnix.mo
generating dist/share/locale/fr/LC_MESSAGES/foobnix.mo
generating dist/share/locale/zh_CN/LC_MESSAGES/foobnix.mo
generating dist/share/locale/de/LC_MESSAGES/foobnix.mo
generating dist/share/locale/ca/LC_MESSAGES/foobnix.mo
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'windows'
  warnings.warn(msg)
running test
Traceback (most recent call last):
  File "setup.py", line 118, in <module>
    'includes': ('cairo, pango, pangocairo, atk, gio, pygst, gst, simplejson, chardet')
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 67, in run
    if not run_all_tests():
  File "/home/maxim/rpmbuild/SOURCES/foobnix-3.1.01/test/all.py", line 16, in run_all_tests
    in module_strings]
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_vk_service'
[maxim@ip204-233 foobnix-3.1.01]$ 

```
что за беда???

**Comment by region51** [comment]
@zavlab1 с приездом, ну так что починишь это???

**Comment by zavlab1** [comment]
Да эта проверка писалась уже очень довно у уже не актуальна для многих сервисов. Я конечно могу сделать, чтобы ошибки не вываливались, но это не сделает все тесты валидными. Скажем так, один тест вообще удалить надо, другой всегда будет выдавать True. Остальные вроде как будут работать.
Если такое решение устроит, то закомичу. А переписывать тесты сейчас желания нет возиться.

**Comment by region51** [comment]
Так с тестом все понятно, полгода и ничего. :-1:
