### ISSUE TITLE
Кое какие warning'и

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#105]
Собственно всегда такой выхлоп

```
[maxim@localhost ~]$ foobnix
which: no xclip in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/maxim/.local/bin:/home/maxim/bin)
which: no xsel in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/maxim/.local/bin:/home/maxim/bin)
start program
/usr/lib64/python2.7/site-packages/pygtkcompat/pygtkcompat.py:231: Warning: The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.props.xalign = xalign
/usr/lib64/python2.7/site-packages/pygtkcompat/pygtkcompat.py:232: Warning: The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.props.yalign = yalign
/usr/lib64/python2.7/site-packages/pygtkcompat/pygtkcompat.py:233: Warning: The property GtkAlignment:xscale is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.props.xscale = xscale
/usr/lib64/python2.7/site-packages/pygtkcompat/pygtkcompat.py:234: Warning: The property GtkAlignment:yscale is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.props.yscale = yscale
/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py:313: Warning: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
/usr/lib/python2.7/site-packages/foobnix/gui/menu.py:165: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  item.set_image(img)
/usr/bin/foobnix:79: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  settings.props.gtk_button_images = True
('******Foobnix run in', 0.5960900783538818, ' seconds******')
[ERROR   ] [13:51:11] [__init__.py:16] Idle task raise an error: 'NoneType' object has no attribute 'info'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/foobnix/util/__init__.py", line 14, in safe_task
    task(*args)
  File "/usr/lib/python2.7/site-packages/foobnix/gui/base_controls.py", line 340, in state_play_pause
    self.statusbar.set_text(bean.info)
AttributeError: 'NoneType' object has no attribute 'info'

```

**Comment by region51** [comment]
Исправлено.
