### ISSUE TITLE
icons problem

### ISSUE THREAD

**Issue by region51** [foobnix/foobnix#129]
```
[maxim@localhost ~]$ foobnix
/usr/lib/python2.7/site-packages/foobnix/dm/dm.py:8: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
[ERROR   ] [22:03:16] [path_service.py:34] File images/hicolor/scalable/apps/foobnix.svg not found
Traceback (most recent call last):
  File "/usr/bin/foobnix", line 92, in <module>
    foobnix()
  File "/usr/bin/foobnix", line 48, in foobnix
    from foobnix.gui.foobnix_core import FoobnixCore
  File "/usr/lib/python2.7/site-packages/foobnix/gui/foobnix_core.py", line 24, in <module>
    from foobnix.gui.notetab import NoteTabControl
  File "/usr/lib/python2.7/site-packages/foobnix/gui/notetab/__init__.py", line 26, in <module>
    from foobnix.gui.treeview.playlist_tree import PlaylistTreeControl
  File "/usr/lib/python2.7/site-packages/foobnix/gui/treeview/playlist_tree.py", line 25, in <module>
    from foobnix.util.converter import convert_files
  File "/usr/lib/python2.7/site-packages/foobnix/util/converter.py", line 29, in <module>
    LOGO = get_foobnix_resourse_path_by_name(ICON_FOOBNIX)
  File "/usr/lib/python2.7/site-packages/foobnix/gui/service/path_service.py", line 35, in get_foobnix_resourse_path_by_name
    raise TypeError("******* WARNING: File " + filename + " not found *******")
TypeError: ******* WARNING: File images/hicolor/scalable/apps/foobnix.svg not found *******
```

**Comment by region51** [comment]
если ложу в images/hicolor/scalable/apps/foobnix.svg
```
[maxim@localhost ~]$ foobnix
/usr/lib/python2.7/site-packages/foobnix/dm/dm.py:8: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
start program
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-play.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-play.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-pause.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-pause.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-stop.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-stop.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-radio.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-radio.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-play.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-play.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-pause.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-pause.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-stop.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-stop.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-radio.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-radio.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-play.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-play.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-pause.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-pause.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-stop.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-stop.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-radio.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-radio.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-play.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-play.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-pause.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-pause.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-stop.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-stop.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-radio.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-radio.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-play.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-play.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-pause.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-pause.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-stop.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-stop.svg not found *******
[ERROR   ] [22:04:57] [path_service.py:34] File images/hicolor/scalable/actions/foobnix-radio.svg not found
[ERROR   ] [22:04:57] [pref_widgets.py:187] ******* WARNING: File images/hicolor/scalable/actions/foobnix-radio.svg not found *******
('******Foobnix run in', 0.39644503593444824, ' seconds******')

(foobnix:1699): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by region51** [comment]
Я хоть убей не понимаю зачем это, абсолютно все делают так
_/usr/share/icons/hicolor/scalable/apps/name.svg_

**Comment by zavlab1** [comment]
1) для того, чтобы в случае отсутствия системной иконки автоматом подгружалась моя. Потому что в одной теме есть, в другой нет, в одной ДЕ есть, в другой нет и т.п.

2) Давай разбираться. Мало инфы. Думаю, что дело в какой-то мелочи.
Сейчас смотрю в свой реп и вижу, что иконки на месте. Что ты тогда и откуда копируешь? Откуда тогда возникла проблема? Ведь ты же до этого запускал и все было нормально.

**Comment by region51** [comment]
просто собрал пакет по умолчанию, результат https://github.com/foobnix/foobnix/issues/129#issue-154318014

**Comment by zavlab1** [comment]
покажи свой спек

**Comment by region51** [comment]
Точно такой же, только коммит и дата другая https://github.com/RussianFedora/foobnix/blob/master/foobnix.spec

**Comment by region51** [comment]
>Ведь ты же до этого запускал и все было нормально.

у меня он уже стоял, и я просто положил твою symbolic иконку в 

_/usr/share/icons/hicolor/symbolic/apps/name-symbolic.svg_

чтобы ее проверить, результат ты видел, хороший.

**Comment by region51** [comment]
@zavlab1 тоесть получается, что все твои иконки вообще нигде не прописаны, чтобы ставились автоматом

**Comment by zavlab1** [comment]
Я не пойму, как твой спек работал до сих пор :)
Не вижу в нем, где ты прописывал раньше те иконки, которые лежали в %{_datadir}/%{name}/images

**Comment by region51** [comment]
%{_datadir}/%{name}

**Comment by zavlab1** [comment]
но ведь они раньше лежали в папке /usr/share/foobnix/images

**Comment by region51** [comment]
ну так и есть

**Comment by zavlab1** [comment]
и сейчас лежат там же, только еще появились подпапки hicolor и scalable

**Comment by region51** [comment]
>только еще появились подпапки hicolor и scalable

вот это вообще не ставится автоматом

**Comment by zavlab1** [comment]
а images получается ставился автоматом? Это ведь нестандартная выдуманная нами папка

**Comment by region51** [comment]
@zavlab1 вот скачай и посмотри https://copr-be.cloud.fedoraproject.org/results/region51/test/fedora-23-x86_64/00215754-foobnix/

**Comment by region51** [comment]
а hicolor и scalable должны быть в 
/usr/share/icons/hicolor/....

**Comment by zavlab1** [comment]
Я под rpm никогда не собирал, поэтому могу что-то не понимать, но почему в foobnix-3.1.2-4.20160511gite017358.fc23.src.rpm эти подпапки есть, а в foobnix-3.1.2-4.20160511gite017358.fc23.noarch.rpm уже нет?

**Comment by region51** [comment]
@zavlab1 вот теперь я тебя не понимаю.

**Comment by region51** [comment]
вся проблема только в том, что у тебя не ставится автоматом hicolor и scalable ВСЕ

**Comment by region51** [comment]
Я могу конечно же их руками прописать, но это совсем не АЙС

**Comment by zavlab1** [comment]
вот смотрю на audacity, virtualbox, geany.
у них в datadir огромная вложенность. Не думаю, что они каждый файл ручками прописывали.

**Comment by zavlab1** [comment]
я думаю, достаточно должно быть добавить одну строку %{_datadir}/%{name}/images/hicolor/scalable

**Comment by zavlab1** [comment]
а, ну можно * на конце поставить

**Comment by region51** [comment]
это %{_datadir}/%{name} цепляет все что есть

**Comment by zavlab1** [comment]
ну пока мы видим, что цепляет только первый уровень вложенности

**Comment by region51** [comment]
полюбому надо шаманить здесь https://github.com/zavlab1/foobnix/blob/master/setup.py

**Comment by zavlab1** [comment]
хорошо, сейчас посмотрю

**Comment by region51** [comment]
>я думаю, достаточно должно быть добавить одну строку %{_datadir}/%{name}/images/hicolor/scalable
>>а, ну можно * на конце поставить

совсем не правильно думаешь

**Comment by region51** [comment]
>хорошо, сейчас посмотрю

блин, ты же .deb собираешь, вот сразу и проверил бы, и все эти вопросы бы отпали

**Comment by region51** [comment]
а то ерунда получается, причем полная

**Comment by zavlab1** [comment]
закомитил. пробуй

**Comment by zavlab1** [comment]
deb собирает launchpad, а не я. Я ему только скармливаю setup.py
Поэтому попробовать не зарелизив не получится :)

**Comment by region51** [comment]
>deb собирает launchpad, а не я. Я ему только скармливаю setup.py
Поэтому попробовать не зарелизив не получится :)

дык, это же совсем не дело

**Comment by zavlab1** [comment]
погоди, не собирай. Ошибку нашел

**Comment by region51** [comment]
да я уже, где все также

**Comment by zavlab1** [comment]
вроде поправил. Можно пробовать

**Comment by region51** [comment]
ты видел какую-нибудь програмулину, где было бы {name}/images/hicolor/scalable?
лично я нет

**Comment by region51** [comment]
за то я видел и вижу с /usr/share/icons/hicolor/... тысячи

**Comment by zavlab1** [comment]
на вскидку:
winetricks
pdfshuffler
gramps

**Comment by zavlab1** [comment]
вообще {name}/images/hicolor использует очень много программ.
просто у большинства программ не векторные, а растровые иконки, поэтому они используют папки типа {name}/images/hicolor/16x16

**Comment by region51** [comment]
теперь все нормально, но эта иконка foobnix-symbolic.svg там лишняя и не работает, так как должна быть в 

/usr/share/icons/hicolor/symbolic/apps/foobnix-symbolic.svg

**Comment by zavlab1** [comment]
короче symbolic иконки gnome ищет только в /usr/share/icons/hicolor/symbolic/
Так что-ли получается?

**Comment by region51** [comment]
ну и /usr/share/icons/hicolor/scalable/apps

**Comment by zavlab1** [comment]
чтобы посмотреть, что получилось, я должен контрастную тему установить?

**Comment by region51** [comment]
@zavlab1 foobnix.svg тоже не работает

**Comment by zavlab1** [comment]
странно, у меня все работает

**Comment by region51** [comment]
проверил неоднократно, на панель выводится иконка из pixmaps

твои лежат без дела
usr/share/foobnix/images/hicolor/....................

**Comment by zavlab1** [comment]
надо смотреть. У меня выводятся именно svg иконки

**Comment by region51** [comment]
сделай как я говорил выше
>Я хоть убей не понимаю зачем это, абсолютно все делают так
/usr/share/icons/hicolor/scalable/apps/name.svg
также рядом symbolic
/usr/share/icons/hicolor/symbolic/apps/name-symbolic.svg

и проблем не будет

**Comment by region51** [comment]
ну и раз есть новые иконки, кокой смысл в pixmaps/foobnix.png?

**Comment by zavlab1** [comment]
тут дело в том, что gnome не подхватил custom_icon_folder в свою тему. Причина - в моем коде.
Надо отладить код за Федорой. Чем сейчас и пытаюсь заниматься.
pixmaps/foobnix.png - это иконка для "меню Пуск" или как там, Обзор вроде.

**Comment by zavlab1** [comment]
Так. У меня под Федорой грузится svg-иконка. Правда запущена прога из сорцов.
Надо symbolic иконки потестить. Как сделать, чтобы они заместо обычных отображались?

**Comment by zavlab1** [comment]
Сделал коммит для дебага. Собери пакет с ним, установи и дай вывод после запуска плеера с опцией --debug и без нее.

**Comment by region51** [comment]
>Сделал коммит для дебага. Собери пакет с ним, установи и дай вывод после запуска плеера с опцией --debug и без нее.

Не получится, я перезагрузился на другой жесткий, где я не провожу вот такие смешные вещи, а почему смешные, да потому что, положил бы сразу иконки эти в /usr/share/icons/hicolor и не было всего этого разговора.

**Comment by zavlab1** [comment]
Как будто у меня сегодня крайний срок релиза, а я мол упрямлюсь. Если бы вопрос был только о 2-х иконках, я бы вообще не заморачивался.
Ты просто не понимаешь, что дело не в том, куда я положу иконки. Это пустяки. Мне нужно универсальное решение, чтобы мои изменения темы подгружались при отсутствии нужных иконок в стандартной теме. И это даже без указания путей к ним! Я ведь делаю плеер, который должен работать во всех ДЕ и их темах одинаково.
Если это получится, то тогда уже не будет ситуации, что ты несколько иконок не видишь, потому что их нет в Gnome. Также и вопрос с главной иконкой и ее simbolic версией отпадет сам собой.
Тут всего-то и осталось, что отладить, а ты соскакиваешь в самый ответственный момент (

P.S.: Если объяснишь, как мне самому собрать rpm по твоему спеку, могу попробовать сам. Скрипт может там нужен какой или зависимости.

**Comment by region51** [comment]
>P.S.: Если объяснишь, как мне самому собрать rpm по твоему спеку, могу попробовать сам. Скрипт может там нужен какой или зависимости.

Не вопрос, стукнись вечерком ко мне в джаббер.
P.S. там нет ничего сложного, обьясню и покажу как ...

**Comment by region51** [comment]
@zavlab1 https://developer.gnome.org/ThemedIcons/
Symbolic Icons

>Symbolic icons have a simple form, and can be used much like text. The will be recolored according to the context in which they are used. By convention, symbolic icons are named with a -symbolic suffix.
Passing an icon name like "pan-start-symbolic" to GTK+ functions like gtk_image_set_from_icon_name() will automatically do the right thing. When you are manually loading a symbolic icon using the GtkIconTheme APIs, make sure to use the 'symbolic' variants, such as gtk_icon_info_load_symbolic() to ensure that the icon is properly colored.
When installing your own symbolic icons, you can either install an svg (the traditional form in which symbolic icons are created) or use the gtk-encode-symbolic-svg utility to convert the icon into specially crafted .symbolic.png files, which can be installed into the fixed-size subdirectories of the icon theme:
gtk-encode-symbolic-svg -o /usr/share/icons/hicolor/48x48/apps my-app-symbolic.svg 48x48

Application icons

>The icon theme spec also provides a universal fallback theme, called hicolor, in which applications can install icons that need to be known by the rest of the system.
The main example for this is the application icon that is used in the applications desktop file. This icon should be named to match the application name, and be installed in /usr/share/icons/hicolor/48x48/apps/. Other sizes are optional.
Applications are also encouraged to install a symbolic version of the application icon into the hicolor theme, with the same name and a -symbolic suffix. The symbolic icon will be used in the HighContrast theme. Symbolic icons can be installed as svgs, in the /usr/share/icons/hicolor/symbolic/apps directory (which was added to hicolor in 0.15), or as .symbolic.png files in /usr/share/icons/hicolor/48x48/apps/. Other sizes are optional.

**Comment by region51** [comment]
ну и еще
_/usr/share/foobnix/images/hicolor/scalable/actions_
надо в
_/usr/share/icons/hicolor/scalable/actions_

**Comment by zavlab1** [comment]
Не спеши. Если надо будет, конечно все сделаю. Сейчас я как раз экспериментирую по этому поводу.
Тут такой вопрос. Ты говорил, что если разместить символическую иконку в /usr/share/icons/hicolor/symbolic/apps или /usr/share/icons/hicolor/scalable/apps, то будет отображаться символическая иконка. Я разместил и там, и там, но Gnome упорно отображает цветную версию. Что я делаю не так? Может где-то в гноме еще надо включить какую-то настройку?

**Comment by region51** [comment]
надо обновить кэш иконок.

**Comment by region51** [comment]
_/bin/touch --no-create /usr/share/icons/hicolor &> /dev/null || :_
или
_/usr/bin/gtk-update-icon-cache /usr/share/icons/hicolor &> /dev/null || :_

**Comment by zavlab1** [comment]
ок.
интересно, что почему-то если прога запущена из исходников, то символическая иконка не грузится, а если через desktop-файл, то грузится.

**Comment by region51** [comment]
@zavlab1 в курсе, что ты опять премудрил.
Теперь у тебя так
_/usr/share/icons/hicolor/scalable/apps_
foobnix.svg
foobnix-symbolic.svg

_/usr/share/icons/hicolor/symbolic/apps_
foobnix-symbolic.svg

зачем 2 symbolic, вполне достаточно 1-й в _/usr/share/icons/hicolor/symbolic/apps_

**Comment by zavlab1** [comment]
На моем компе сейчас все по-другому. Когда доделаю, дам отмашку.
Ну а по сути я это сделал для совместимости со старыми версиями Gnome и другими DE. Т.к. папка symbolic появилась только с 15 версии. Например, в KDE ее нет, а контрастные темы есть.

**Comment by region51** [comment]
и сдается мне, что 
/usr/share/icons/hicolor/symbolic/actions
здесь вообще не должно быть

**Comment by zavlab1** [comment]
я просто подумал, что т.к. символические иконки ищутся только в symbolic, то что же мне делать с моими другими символическими иконками. Иначе они просто не будут отображаться. Тут только вариант класть в scalable/actions, но с другой стороны, теперь есть специальная папка, поэтому кладу туда.

**Comment by region51** [comment]
ну я глянул по Fedora, никто туда ничего не кладет, там только одно, это
/usr/share/icons/hicolor/symbolic/apss

**Comment by region51** [comment]
>Ну а по сути я это сделал для совместимости со старыми версиями Gnome и другими DE. Т.к. папка symbolic появилась только с 15 версии. Например, в KDE ее нет, а контрастные темы есть.

и все же, я думаю нужна только одна иконка.
P.S. ну если решил оставить дело твое, но я все равно ее на этапе сборки выкину, так как негоже дублировать.

**Comment by zavlab1** [comment]
Кажется доделал. Можно собирать и тестировать.

**Comment by region51** [comment]
>Кажется доделал. Можно собирать и тестировать.

тоесть оставил все как было.

**Comment by region51** [comment]
_IMHO_
было (лучше), потому что родные иконки
![99e15642-0b0d-11e6-829c-17f1093aa84d](https://cloud.githubusercontent.com/assets/13280183/15242715/5c65cb30-1900-11e6-8f7b-dd93b0729d5b.png)
стало (хуже), потому что винегрет из разных иконок
![screenshot from 2016-05-13 11-44-17](https://cloud.githubusercontent.com/assets/13280183/15242671/2d5aec30-1900-11e6-90fc-03fb90e76c7a.png)
трей
![screenshot from 2016-05-13 11-47-41](https://cloud.githubusercontent.com/assets/13280183/15242777/a6e370d6-1900-11e6-9187-85ee243be947.png)

**Comment by zavlab1** [comment]
>тоесть оставил все как было.
_/usr/share/foobnix/images/hicolor/scalable/actions_
_/usr/share/icons/hicolor/scalable/actions_
_/usr/share/icons/hicolor/symbolic/actions_
_/usr/share/icons/hicolor/scalable/apps_
_/usr/share/icons/hicolor/symbolic/apps_

>И еще до кучи hicolor
_/usr/share/foobnix/images/hicolor/scalable/actions_
Не многовато ли hicolor раскидал?

Ну а что делать? Я же не только для тебя плеер пишу. Мне нужна совместимость со всеми ДЕ всех версий. Скорее всего перенесу иконки из symbolic/actions в scalable/actions.
Насчет кастомного hicolor - необходимо для замены отсутствующих в стандартной теме иконок.
Теперь насчет было лучше: последние две иконки - как раз родные гномовские и именно для тех функций, которые реализуют эти кнопки. Раньше вообще стояли иконки "Обновить" и "Вернуть изменения". Теперь же стоят именно нужные иконки Gnome: Media-shuffle и Media-repeat. Так что они как раз в тему и выглядят родными.
Если говорить об иконке для меню, то раньше не было иконок application-menu. Поэтому приходилось использовать иконку System-settings. Но она не отражает смысла функции - отображение меню. Теперь иконка application-menu появилась, но пока в Gnome она не раелизована (в KDE уже есть). Поэтому используется универсальная иконка меню. Как только Gnome реализует иконку, подгружаться будет именно она.
Про иконку Love забыл. Надо будет подобрать какую-нибудь подходящую.

>c foobnix-pause-symbolic.svg явно БЕДА, потому что она не symbolic.

Согласен, надо разобраться.

>Их же руками надо указывать.
Поэтому вопрос. Кто в здравом уме догадается, что эти иконки лежат в
/usr/share/icons/hicolor/symbolic/actions
и т.п.

Функционал переменных иконок трея мне еще нужно будет потестировать и доработать.
Тут сложность. Gnome автоматом использует символические иконки только для уже установленного приложения. Из исходников тестировать не получится. Поэтому надо каждый раз для теста собирать и переустанавливать пакет. Так что видимо все-таки надо будет тебе меня этому научить.

**Comment by region51** [comment]
>Так что видимо все-таки надо будет тебе меня этому научить

ну я могу делать пакеты и передавать тебе их сразу в джаббере.
ну и я в стороне не останусь, тоже потестю ...

**Comment by zavlab1** [comment]
Ну если не задолбаешься каждые пять минут делать, тогда ОК :)

Кстати, иконка для меню уже появилась в 3.20, так что скоро левая кнопка будет соотвествовать.
Если у тебя уже 3.20, а кнопка не из темы, то обнови плеер из моей ветки.
Иконку Love нашел.

**Comment by region51** [comment]
>Ну если не задолбаешься каждые пять минут делать, тогда ОК :)

сколько надо, столько и сделаем

>Если у тебя уже 3.20

нет, Fedora 24 выйдет только через месяц

**Comment by region51** [comment]
>Иконку Love нашел.

вижу
![2016-05-13-155309_1280x1024_scrot](https://cloud.githubusercontent.com/assets/13280183/15248450/f46e97be-1922-11e6-8d7c-c3c021349438.png)

>Кстати, иконка для меню уже появилась в 3.20, так что скоро левая кнопка будет соотвествовать.

чего-то я недопонимаю, о чем речь? где, какое меню?

**Comment by zavlab1** [comment]
Ну ты жаловался чуть выше:
>винегрет из разных иконок, особенно первая выбивается

С версии 3.20 уже не будет выбиваться

**Comment by region51** [comment]
ааа, теперь понятно о чем речь.

**Comment by region51** [comment]
а зачем у тебя в https://github.com/zavlab1/foobnix/blob/master/setup.py
_('share/icons/hicolor/48x48/apps', glob.glob('share/icons/hicolor/48x48/apps/*.*')),_
ты чего-то туда будешь ложить?

**Comment by zavlab1** [comment]
На выходе должна быть. Видимо в git забыл добавить. Сейчас поправил.
_Ты мне вчера кусок документации показывал. Там сказано, что desktop файл из этой папки берет изображение. Ну я туда и кинул png. Сделал как в доке. Но пока до конца не определился, какое изображение к desktop файлу прикручивать. svg или png. Второе как бы посложнее (тени там, блики)... Но не уверен, что это лучше. Вобщем пока думаю._

**Comment by region51** [comment]
>Ты мне вчера кусок документации показывал. Там сказано, что desktop файл из этой папки берет изображение. Ну я туда и кинул png. Сделал как в доке.

не надо делать все, как когда то было написано. Лично я считаю это hicolor/48x48 лишним совсем, достаточно  _/usr/share/icons/hicolor/scalable/apps/foobnix.svg_

**Comment by region51** [comment]
@zavlab1 так и давай точно определимся. Ты оставляешь вот эту икону, которая идет у тебя дважды _/usr/share/icons/hicolor/scalable/apps/foobnix-symbolic.svg_ ???
Так как я ее, ТОЧНО буду убирать за не надобностью.

**Comment by zavlab1** [comment]
Да, эту я оставлю для совместимости с old Gnome и not Gnome дистрами. И тебе ее советую не трогать, т.к. тем самым ты оставишь без символической икони тех, кто на Fedora < 22 версии, тех, кто на RedHat < 6.7, а также CentOS'овцев. Т.е. минусов несравненно больше, чем плюсов от экономии 2-3 кБ. Это тот случай, когда перфекционизм вреден.

**Comment by region51** [comment]
>Fedora < 22
>RedHat < 6.7

я не делаю для них

**Comment by zavlab1** [comment]
Просто вреда не будет, если ее оставить, а людям может твой пакет пригодиться.
Скажем так, это можно сделать без собственной выгоды, чисто из великодушия.

**Comment by region51** [comment]
@zavlab1 у меня Fedora ругается на

_foobnix.noarch: E: script-without-shebang /usr/share/foobnix/images/hicolor/scalable/emotes/emote-love.svg_
_foobnix.noarch: E: script-without-shebang /usr/share/foobnix/images/hicolor/scalable/actions/application-menu.svg_

**Comment by zavlab1** [comment]
попробуй снять право на выполнение с этих файлов или просто обновись из моей ветки

**Comment by region51** [comment]
@zavlab1 еще нашел одну мелочь, запускаешь плеер, значок в трее есть. Дальше открываешь настройки, меняешь там что-нибудь и значок теряет свою видимость.  Нужен перезапуск. Не хорошое поведение.

**Comment by region51** [comment]
@zavlab1 Rename tab icon missing
![2016-05-15-220025_1280x1024_scrot](https://cloud.githubusercontent.com/assets/13280183/15276160/aa043bee-1ae8-11e6-995e-dbb3b0f1fde9.png)
?

**Comment by zavlab1** [comment]
При тесте из исходников поведение нормальное. Так что нужен пакет. Только обновись сначала. Жду письма.

По иконке: Удивительно, но для символической иконки test-editor не существует несимволической версии. Переделал код по simbolic.

**Comment by region51** [comment]
>Так что нужен пакет.

Тебе? 
P.S. Если да, то не проблема, я же говорил постучись ко мне в джабер.

**Comment by zavlab1** [comment]
> еще нашел одну мелочь, запускаешь плеер, значок в трее есть. Дальше открываешь настройки, меняешь там что-нибудь и значок теряет свою видимость. Нужен перезапуск. Не хорошое поведение.

Что-то воспроизвести не получается. Вроде все нормально.

**Comment by region51** [comment]
>Вроде все нормально.

Ничего не нормально, все как было так и есть, значок пропадает после того, как меняешь что-нибудь в настройках.

**Comment by region51** [comment]
И кстати раньше выхлоп был нормальный/пустой без этого, что выше.

**Comment by zavlab1** [comment]
> (foobnix:3741): Gtk-WARNING **: Theme parsing error: <data>

Это уже поправлено.

> Значок пропадает, когда меняешь что-нибудь в настройках.

Попробовал из исходников. Меняю в настройках что-нибудь. Нажимаю Apply. Значок на месте.
То же самое после установки пакета и запуске из Dash. Непонятно, что фиксить-то.

**Comment by region51** [comment]
Я могу показать видео, но на нем будет то, что я написал.

**Comment by region51** [comment]
>Это уже поправлено.

где? у меня все последнее.

**Comment by zavlab1** [comment]
Да я тебе верю. Только вот что делать, если воспоизвести не получается.

> (foobnix:3741): Gtk-WARNING **: Failed to fetch network locations: Timeout was reached

Попробуй-ка сбросить конфиг, не пропадет ли этот мессадж. Я недавно скрывал пароль за md5. Возможно у тебя в конфиге еще пароль в открытой форме остался.

> где? у меня все последнее.

Пока на компе. Со следующим комитом будет в git. 
Не беспокойся. Это всего лишь message, который не на что не влияет.

**Comment by region51** [comment]
>Попробуй-ка сбросить конфиг, не пропадет ли этот мессадж. Я недавно скрывал пароль за md5. Возможно у тебя в конфиге еще пароль в открытой форме остался.

удалил конфиг, тоже самое.

**Comment by zavlab1** [comment]
Работает ли поиск и воспроизведение удаленных треков?

**Comment by region51** [comment]
>Работает ли поиск и воспроизведение удаленных треков?

это что? я не могу понять.

**Comment by zavlab1** [comment]
Ты что, только локальную музыку слушаешь? Строка поиска над плейлистом.

Ты всю папку конфига удалил или только foobnix.pkl ? Просто пароль хранится в foobnix_base.pkl. Его и надо удалять.

**Comment by region51** [comment]
>Ты что, только локальную музыку слушаешь?

да, только ее.

>Ты всю папку конфига удалил

да ее родную.

**Comment by region51** [comment]
>Работает ли поиск и воспроизведение удаленных треков?
>>Строка поиска над плейлистом

Поиск работает, воспроизведение не знаю, так как появляется окно авторизации VK, где я не зарегистрирован.

**Comment by zavlab1** [comment]
Баг с пропадающей иконкой смог воспроизвести на Kubuntu. Пофиксил.

**Comment by region51** [comment]
>Баг с пропадающей иконкой смог воспроизвести на Kubuntu. Пофиксил.

молодец.

**Comment by region51** [comment]
@zavlab1 привет, поменяй права у этой иконки
_/usr/share/foobnix/images/hicolor/scalable/actions/gtk-convert.svg_

**Comment by zavlab1** [comment]
Поменял.
