### ISSUE TITLE
foobnix & manjaro  16.10 x64 xfce

### ISSUE THREAD

**Issue by urgentus** [foobnix/foobnix#134]
Hi! Thanks for foobnix.
Probably, in Manjaro 16.10 x64 foobnix don`t start.

> [chapa@pc-m1610 ~]$ foobnix
/usr/lib/python2.7/site-packages/foobnix/gui/base_controls.py:17: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "/usr/bin/foobnix", line 98, in <module>
    foobnix()
  File "/usr/bin/foobnix", line 50, in foobnix
    from foobnix.gui.foobnix_core import FoobnixCore
  File "/usr/lib/python2.7/site-packages/foobnix/gui/foobnix_core.py", line 8, in <module>
    from foobnix.gui.base_controls import BaseFoobnixControls
  File "/usr/lib/python2.7/site-packages/foobnix/gui/base_controls.py", line 28, in <module>
    from foobnix.gui.service.vk_service import VKService
  File "/usr/lib/python2.7/site-packages/foobnix/gui/service/vk_service.py", line 12, in <module>
    gi.require_version("WebKit", "3.0")
  File "/usr/lib/python2.7/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace WebKit not available for version 3.0

> 

Help. Thanks.

**Comment by zavlab1** [comment]
Do you use Foobnix installed from package or from sources? Most likely you use rather old package.
There are two things in your message.
First - "Use gi.require_version('Notify', '0.7') ...". It was done for a long time ago in current developer branch.
Second - "ValueError: Namespace WebKit not available for version 3.0". This means that there is no needed package for gtk webkit in your system. (That is why player doesn't starts).
In deb-distros name for this package is gir1.2-webkit-3.0. For Arch and Manjaro I not sure what is name of the package, bot most likely it is webkitgtk.

**Comment by urgentus** [comment]
Thanks. I can`t find gir1.2-webkit-3.0 for Manjaro. Progs DebTab is only for ArchLinux (.
Foobnix had installed from AUR (ver. 3.1-1)

**Comment by zavlab1** [comment]
gobject-introspection package is installed?

**Comment by urgentus** [comment]
gobject-introspection package is installed? Yes. And gobject-introspection-runtime.
Thanks for help.

**Comment by urgentus** [comment]
Go back to Manjaro 16.08. Foobnix works well.

**Comment by urgentus** [comment]
Foobnix dont works on Manjaro 16.10.2 too.

**Comment by urgentus** [comment]
Foobnix dont works on Manjaro 16.10.3 too.

**Comment by urgentus** [comment]
How fix it? Please.

**Comment by zavlab1** [comment]
I think the reason is dependences in new version Manjaro (16.10). If an error log is the same as in first message of issue, then you need know what package is using for gobject introspection of Webkit-gtk in this distributive.
I never made pkgbild for Arch or Manjaro, that is why I can't help in details. Sorry.

**Comment by urgentus** [comment]
Foobnix works fine Manajro 16.10.3 x64 xfce.
Install next package:
gambas3-gb-qt4-webkit  3.9.1-4
gambas3-gb-qt5-webkit  3.9.1-4
webkit2gtk  2.14.3-1
qtwebkit  2.3.4-4
qt5-webkit  5.7.1-1

SOLVED

**Comment by zavlab1** [comment]
Congratulations.
I think, only two of all the packages you mentioned really led to the result.
webkit2gtk 2.14.3-1
webkitgtk
Others are associated with Qt libraries, which are not used in the program

**Comment by urgentus** [comment]
zavlab1, thanks.

**Comment by urgentus** [comment]
gambas3-gb-qt4-webkit 3.9.1-4
gambas3-gb-qt5-webkit 3.9.1-4

This packages must be installed too.

**Comment by urgentus** [comment]
Install 
webkit2gtk 
webkitgtk

Foobnix works in Manjaro 17.0 x64.

**Comment by zavlab1** [comment]
Congratulations.
Will you share the packages and PKGBUILD for Manjaro (and probably Arch)?

**Comment by urgentus** [comment]
Foobnix works nice on Manjaro 17.02 x64 xfce.
You have installed webkitgtk before, and then have install Foobnix.

**Comment by urgentus** [comment]
> Will you share the packages and PKGBUILD for Manjaro (and probably Arch)?

I can`t this works. Sorry.

**Comment by urgentus** [comment]
Package "webkitgtk" had been removed from repo in last updates Manjaro.
Foobnix don`t works, but we have a succeful decide.

1. Edit pacman-mirrors.conf
sudo leafpad /etc/pacman-mirrors.conf

We replace "Branch = stable" with "Branch = testing"
 & save the file.

2. sudo pacman -S downgrade

3. /usr/bin/downgrade webkitgtk
   choose number of package
   install it

4. Put "webkitgtk" in ignored packages.

5. Jf you want, we can reverse changing in pacman-mirrors.conf on "Branch = stable".

6. Install Foobnix from AUR.

Sorry for my bad English.

**Comment by urgentus** [comment]
> urgentus commented on 22 Aug 2017

> 
This rule works on Manjaro 17.1.5 x64 too.

**Comment by urgentus** [comment]
Manjaro 17.1.11 x64
WebKit is inherently big and complex, compilation is very long.
Desicion:
1. sudo leafpad /etc/pacman.conf
2. in the end of file:
[archlinuxcn]
Server = https://cdn.repo.archlinuxcn.org/$arch
3. sudo pacman -Syyuu
4. sudo pacman -S webkitgtk
    sudo pacman -S webkitgtk2
5./usr/bin/downgrade webkitgtk
choose number of package
install it
6. Put "webkitgtk" in ignored packages.
7.  yaourt -S foobnix

Good luck.
